### ISSUE TITLE
Using with Steam Deck, seems to break the Deck's native controller support.

### ISSUE THREAD

**Issue by Xbob42** [Lyall/BravelyDefault2Fix#1]
Hi! I know this isn't really made for the Deck but I'm using it to get that sweet, sweet 16:10 support.

However, upon installing it and adding `WINEDLLOVERRIDES="xinput1_3=n,b" %command%` to my Steam Launch options, I lose the ability to control the game with my Steam Deck's native controls. I can still use a mouse and keyboard, and the game is definitely running in full 16:10. Is there a way around this issue?

**Comment by Lyall** [comment]
Yes! I've actually been using it on my Steam Deck myself. You can rename the DLL to ``dxgi.dll`` . You shouldn't need any launch options with that name either.

I've just added vertical offsetting of the HUD to constrain it to 16:9 and the FOV should be vert+ now. I'll be putting up a Steam Deck release that is already renamed to dxgi.dll just to make things simpler.

On a side note, I actually added a resolution scaling option because of the Steam Deck. The high graphics preset in Bravely Default 2 sets r.ScreenPercentage to 130, effectively downsampling. You can run this at 100 (or even lower) on the Deck for much improved performance.

![download](https://user-images.githubusercontent.com/695941/184308190-6cea36ac-c5a5-41c1-a27e-a8544173a3a4.jpeg)

Edit: [New release](https://github.com/Lyall/BravelyDefault2Fix/releases/) is up if you'd like to try it.

**Comment by Xbob42** [comment]
Beautiful! Thank you! That worked perfectly. It runs SO well! Thanks for this mod!
